export const RESIZE = 'RESIZE';
export const STYLE_REQUEST = 'STYLE_REQUEST';
export const STYLE_SET = 'STYLE_SET';
export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const SET_COMP_DIMENSIONS = 'SET_COMP_DIMENSIONS';
export const INSTRUCTION_CLICKED = 'INSTRUCTION_CLICKED';

export const COPY_REQUEST = 'COPY_REQUEST';
export const COPY_SET = 'COPY_SET';
export const SETTINGS_REQUEST = 'SETTINGS_REQUEST';
export const SETTINGS_SET = 'SETTINGS_SET';

export const API_SETTINGS_REQ = 'API_SETTINGS_REQ';
export const API_SETTINGS_POST = 'API_SETTINGS_POST';

export const API_ALL_SCHOOLS_REQUEST = 'API_ALL_SCHOOLS_REQUEST';
export const API_ALL_SCHOOLS_SUCCESS = 'API_ALL_SCHOOLS_SUCCESS';


export const COMP_TOGGLE_MENU = 'COMP_TOGGLE_MENU';
export const COMP_TOGGLE_CALENDAR_VISIBILITY =
  'COMP_TOGGLE_CALENDAR_VISIBILITY';
export const COMP_OPEN_MODAL = 'COMP_OPEN_MODAL';
export const COMP_CLOSE_MODAL = 'COMP_CLOSE_MODAL';
export const COMP_SHOW_SPINNER = 'COMP_SHOW_SPINNER';
export const COMP_HIDE_SPINNER = 'COMP_HIDE_SPINNER';

export const AUTH_UPDATE_IPEDS = 'AUTH_UPDATE_IPEDS';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const PREMIUM_PARTNER_REQUEST = 'PREMIUM_PARTNER_REQUEST';
export const PREMIUM_PARTNER_SUCCESS = 'PREMIUM_PARTNER_SUCCESS';
export const PREMIUM_PARTNER_ERROR = 'PREMIUM_PARTNER_ERROR';
export const DASHB_VIEWBOOK_SELECTED_INDEX = 'DASHB_VIEWBOOK_SELECTED_INDEX';
export const DASHB_VIEWBOOK_DRAG_SELECTED_INDEX =
  'DASHB_VIEWBOOK_DRAG_SELECTED_INDEX';
export const DASHB_VIEWBOOK_INDEX_GRABBED_OVER =
  'DASHB_VIEWBOOK_INDEX_GRABBED_OVER';
export const DASHB_VIEWBOOK_INDEX_GRABBED = 'DASHB_VIEWBOOK_INDEX_GRABBED';
export const DASHB_VIEWBOOK_INDEX_CHANGED = 'DASHB_VIEWBOOK_INDEX_CHANGED';
export const DASHB_VIEWBOOK_MEDIA_DELETE = 'DASHB_VIEWBOOK_MEDIA_DELETE';
export const DASHB_VIEWBOOK_MEDIA_UPDATE = 'DASHB_VIEWBOOK_MEDIA_UPDATE';

export const DASHB_VIEWBOOK_IMAGE_CHOSEN = 'DASHB_VIEWBOOK_IMAGE_CHOSEN';
export const DASHB_VIEWBOOK_IMAGE_LINK = 'DASHB_VIEWBOOK_IMAGE_LINK';
export const DASHB_VIEWBOOK_IMAGE_LINK_CONFIRMED =
  'DASHB_VIEWBOOK_IMAGE_LINK_CONFIRMED';
export const DASHB_VIEWBOOK_IMAGE_UPLOAD = 'DASHB_VIEWBOOK_IMAGE_UPLOAD';
export const DASHB_VIEWBOOK_IMAGE_UPLOAD_SUCCESS =
  'DASHB_VIEWBOOK_IMAGE_UPLOAD_SUCCESS';
export const DASHB_VIEWBOOK_IMAGE_UPLOAD_ERROR =
  'DASHB_VIEWBOOK_IMAGE_UPLOAD_ERROR';

export const DASHB_VIEWBOOK_VIDEO_LINK = 'DASHB_VIEWBOOK_VIDEO_LINK';
export const DASHB_VIEWBOOK_VIDEO_LINK_VALID =
  'DASHB_VIEWBOOK_VIDEO_LINK_VALID';
export const DASHB_VIEWBOOK_VIDEO_LINK_CONFIRMED =
  'DASHB_VIEWBOOK_VIDEO_LINK_CONFIRMED';

export const DASHB_VIEWBOOK_PUBLISH = 'DASHB_VIEWBOOK_PUBLISH';

export const LEAD_DATA_REQUEST = 'LEAD_DATA_REQUEST';
export const LEAD_DATA_ERROR = 'LEAD_DATA_ERROR';
export const LEAD_DATA_SUCCESS = 'LEAD_DATA_SUCCESS';
export const LEAD_DATA_DATE_SELECT = 'LEAD_DATA_DATE_SELECT';
export const LEAD_DATA_TABLE_SET_FILTERED_DATA =
  'LEAD_DATA_TABLE_SET_FILTERED_DATA';
export const LEAD_DATA_TABLE_FILTER_HEADERS = 'LEAD_DATA_TABLE_FILTER_HEADERS';
export const LEAD_DATA_TABLE_FILTER_SETTINGS =
  'LEAD_DATA_TABLE_FILTER_SETTINGS';
export const LEAD_DATA_DOWNLOAD_CSV = 'LEAD_DATA_DOWNLOAD_CSV';
export const LEAD_DATA_DOWNLOAD_CSV_ERROR = 'LEAD_DATA_DOWNLOAD_CSV_ERROR';
export const LEAD_DATA_FILTER_WARN = 'LEAD_DATA_FILTER_WARN';
export const IS_LOADING_LEADS = 'IS_LOADING_LEADS';
export const IS_DONE_LOADING_LEADS = 'IS_DONE_LOADING_LEADS';
export const SET_YEAR_RANGE = 'SET_YEAR_RANGE';
export const SET_YEAR_RANGE_VALUES = 'SET_YEAR_RANGE_VALUES';
export const SET_YEARLY_LEAD_DATA = 'SET_YEARLY_LEAD_DATA';

export const PERFORMANCE_HEARTS_REQUEST = 'PERFORMANCE_HEARTS_REQUEST';
export const PERFORMANCE_HEARTS_SUCCESS = 'PERFORMANCE_HEARTS_SUCCESS';
export const PERFORMANCE_HEARTS_ERROR = 'PERFORMANCE_HEARTS_ERROR';
